#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Constants.h"

// Test generating some register information

void createRegisters(llvm::Module &M) {new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, false)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"PC");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"SP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R0");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R1");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R2");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R3");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R4");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R5");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R6");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R7");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R8");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R9");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R10");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R11");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R12");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R13");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"ACR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"SP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R0");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R1");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R2");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R3");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R4");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R5");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R6");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R7");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R8");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R9");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R10");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R11");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R12");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"R13");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"CCR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"MOF");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"IBR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"IRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"BAR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"DCCR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"BRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"USP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"VR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"SRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P0");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P2");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P3");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P4");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P6");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P8");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"CCR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"MOF");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"IBR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"IRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"BAR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"DCCR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"BRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"USP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"VR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"SRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P0");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P2");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P3");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P4");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P6");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P8");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"CCR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"MOF");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"IBR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"IRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"BAR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"DCCR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"BRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"USP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"VR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"SRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P0");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P2");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P3");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P4");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P6");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P8");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"CCR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"MOF");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"IBR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"IRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"BAR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"DCCR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"BRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"USP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"VR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"SRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P0");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P2");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P3");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P4");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P6");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"P8");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"BZ");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"PID");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"SRS");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"WZ");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"EXS");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"EDA");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"MOF");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"DZ");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"EBP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"ERP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"NRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"CCS");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"USP");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"SPC");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"VR");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"SRP");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt1Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(1, 0, true)),
"pc");
new llvm::GlobalVariable(M,
llvm::Type::getInt32Ty(llvm::getGlobalContext()),
false,
llvm::GlobalValue::LinkageTypes::ExternalLinkage,
llvm::ConstantInt::get(llvm::getGlobalContext(), llvm::APInt(32, 0, true)),
"pc");
}